### ISSUE TITLE
2019.3

### ISSUE THREAD

**Issue by ghost** [stachenov/maven-dependency-updater#1]
Needs update to IntelliJ 2019.3.

You are experiencing the following error message:

13:09 Plugin Error: "Maven Dependency Updater" plugin is incompatible (target build range is 192.5728 to 192. *).

---------------------------------------------------------------

Требуется обновление до IntelliJ 2019.3.

Вы видите следующее сообщение об ошибке:

13:09 Ошибка плагина: плагин «Maven Dependency Updater» несовместим (целевой диапазон сборки от 192,5728 до 192. *).

**Comment by stachenov** [comment]
Oops. I was kind of busy when 2019.3 was out and then I just forgot. Done now. Will be available as soon as it passes JB moderation (usually on the next day).

**Comment by ghost** [comment]
Tanks

**Comment by stachenov** [comment]
Published now.
